name: of_flutter_mobile
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.4.0
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.4
  morphable_shape: ^1.6.6
  gap: ^3.0.1
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  permission_handler: ^11.2.0
  pull_to_refresh: ^2.0.0
  month_picker_dialog: ^2.6.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  flutter_animate: ^4.4.0
  flutter_barcode_scanner: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_downloader: ^1.11.6
  font_awesome_flutter: ^10.6.0
  flutter_typeahead: ^5.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_easyloading: ^3.0.5
  awesome_dialog: ^3.2.0
  animated_floating_buttons: ^0.0.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.4
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter.ttf
    - family: Oswald
      fonts: 
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: Lato
      fonts: 
        - asset: assets/fonts/Lato-Regular.ttf
    
  uses-material-design: true

